name: Vlgui

default-extensions:
  - AllowAmbiguousTypes
  - Arrows
  - BlockArguments
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DerivingStrategies
  - DerivingVia
  - DuplicateRecordFields
  - EmptyCase
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - ImportQualifiedPost
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PatternSynonyms
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - UndecidableInstances
  - ViewPatterns

source-dirs:
  - src

dependencies:
  - vector
  - OpenGL
  - text
  - StateVar
  - base
  - bearriver
  - distributive
  - indexed-traversable
  - dunai
  - hgeometry
  - hgeometry-combinatorial
  - lens
  - linear
  - nanovg
  - vinyl
  - relude
  - sdl2
  - colour
  - Stream
  - vector-circular

ghc-options:
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N

executables:
  Vlgui-exe:
    source-dirs: app
    main: Main.hs

tests:
  Vlgui-test:
    source-dirs: test
    main: Spec.hs
    dependencies:
      - tasty
      - tasty-hunit
